# Generated by Django 4.2.16 on 2026-03-24 13:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('PAYROLL', 'Payroll System'), ('HR_SYSTEM', 'HR System'), ('COMMUNICATION', 'Communication'), ('SECURITY', 'Security'), ('ERP', 'ERP System')], max_length=50)),
                ('status', models.CharField(choices=[('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('PENDING', 'Pending'), ('ERROR', 'Error')], default='DISCONNECTED', max_length=20)),
                ('endpoint_url', models.URLField(blank=True, help_text='Base API URL for the integration', null=True)),
                ('api_key', models.CharField(blank=True, help_text='API key or webhook URL', max_length=512, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
