# Generated by Django 4.2.16 on 2026-03-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_externalintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='profile_photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
