# Generated by Django 4.2.16 on 2026-03-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employeedetail_bio_employeedetail_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='notification_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='regional_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
