# Generated by Django 4.2.16 on 2026-03-28 14:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_department_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(db_column='_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(db_column='departmentId', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='accounts.department')),
            ],
            options={
                'unique_together': {('name', 'department')},
            },
        ),
    ]
