# Generated by Django 4.2.16 on 2026-03-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('ANNUAL', 'Annual'), ('SICK', 'Sick'), ('MATERNITY', 'Maternity'), ('PATERNITY', 'Paternity'), ('COMPASSIONATE', 'Compassionate'), ('UNPAID', 'Unpaid')], default='ANNUAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50),
        ),
    ]
