# Generated by Django 4.2.16 on 2026-03-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_alter_leaverequest_leave_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='value',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='policy',
            name='rules',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
