# Generated by Django 4.2.16 on 2026-03-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_policy_description_policy_is_active_policy_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='rules',
            field=models.JSONField(default=dict),
        ),
    ]
