# Generated by Django 4.2.16 on 2026-03-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_alter_policy_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='category',
            field=models.CharField(choices=[('ATTENDANCE', 'Attendance & Punctuality'), ('LEAVE', 'Leave & Time Off'), ('ADMINISTRATIVE', 'Administrative & HR'), ('COMPENSATION', 'Compensation & Benefits'), ('SECURITY', 'Security & Emergency')], default='ATTENDANCE', max_length=50),
        ),
        migrations.AddField(
            model_name='policy',
            name='urgency',
            field=models.CharField(choices=[('CRITICAL', 'Critical/Immediate'), ('HIGH', 'High Priority'), ('MEDIUM', 'Standard/Medium'), ('LOW', 'Low Priority')], default='MEDIUM', max_length=50),
        ),
    ]
