# Generated by Django 4.2.16 on 2026-03-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_policy_category_policy_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='category',
            field=models.CharField(choices=[('ATTENDANCE', 'Attendance'), ('BIOMETRIC', 'Biometric Enrollment'), ('NOTIFICATION', 'Notification'), ('LEAVE', 'Leave'), ('HR_ADMIN', 'HR Admin'), ('PAY_BENEFITS', 'Pay/Benefits'), ('SAFETY', 'Safety'), ('HEALTH_WELFARE', 'Health & Welfare'), ('ETHICS', 'Ethics')], default='ATTENDANCE', max_length=50),
        ),
        migrations.AlterField(
            model_name='policy',
            name='urgency',
            field=models.CharField(choices=[('EXTREME', 'Extreme/Immediate'), ('CRITICAL', 'Critical/Legal'), ('HIGH', 'High Priority'), ('MEDIUM', 'Standard/Medium'), ('LOW', 'Low Priority'), ('OPTIONAL', 'Optional/Benefit')], default='MEDIUM', max_length=50),
        ),
    ]
