# Generated by Django 4.2.16 on 2026-03-27 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_add_reason_to_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
