# Generated by Django 4.2.16 on 2026-05-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_add_rejection_reason'),
        ('leave', '0008_leaverequest_attachment'),
    ]

    operations = [
    ]
