# Generated by Django 4.2.16 on 2026-03-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('ON_TIME', 'On-time'), ('LATE', 'Late'), ('EARLY_EXIT', 'Early-exit'), ('OVERTIME', 'Overtime')], max_length=50),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='type',
            field=models.CharField(choices=[('CHECK_IN', 'Check-in'), ('CHECK_OUT', 'Check-out')], max_length=50),
        ),
    ]
