# Generated by Django 4.2.16 on 2026-03-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancerecord_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='verification_status',
            field=models.CharField(choices=[('VERIFIED', 'Verified'), ('UNVERIFIED', 'Unverified (Bypass)'), ('PENDING', 'Pending Validation')], default='VERIFIED', max_length=50),
        ),
    ]
