# Generated by Django 4.2.16 on 2026-05-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='method',
            field=models.CharField(default='face', help_text='Method used: face, fingerprint, manual', max_length=50),
        ),
    ]
