# Generated by Django 4.2.16 on 2026-05-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendancerecord_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('ON_TIME', 'On-time'), ('LATE', 'Late'), ('EARLY_EXIT', 'Early-exit'), ('OVERTIME', 'Overtime'), ('ABSENT', 'Absent')], max_length=50),
        ),
    ]
