# Generated by Django 4.2.16 on 2026-03-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='grace_period',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='shift',
            name='work_days',
            field=models.CharField(default='Mon - Fri', max_length=100),
        ),
    ]
