# Generated by Django 4.2.16 on 2026-04-11 20:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_shift_description_shift_grace_period_shift_work_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(db_column='_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(unique=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='If true, this holiday repeats every year on this date.')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
